language: node_js
node_js:
  - "node"
branches:
  only:
    - master
stages:
  - test
  - build
jobs:
  include:
    - stage: test
      name: Run frontend tests
      install:
        - cd frontend
        - npm install
      script:
        - npm test
    - stage: test
      name: Run backend tests
      install:
        - cd backend
        - npm install
      script:
        - npm test
    - stage: build
      name: Build frontend
      install:
        - cd frontend
        - npm install
      script:
        - npm run build
    - stage: build
      name: Build backend
      install:
        - cd backend
        - npm install
      script:
        - npm run build
notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt